"""Initial schema

Revision ID: 6e371861fda8
Revises: 
Create Date: 2026-06-26 13:50:25.272449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e371861fda8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracks')
    op.drop_table('external_identities')
    op.drop_index(op.f('idx_release_labels_label_key'), table_name='release_labels')
    op.drop_table('release_labels')
    op.drop_table('review_queue')
    op.drop_index(op.f('idx_unresolved_artists_normalized'), table_name='unresolved_artists')
    op.drop_table('unresolved_artists')
    op.drop_index(op.f('idx_release_artists_artist_key'), table_name='release_artists')
    op.drop_table('release_artists')
    op.drop_index(op.f('idx_unresolved_labels_normalized'), table_name='unresolved_labels')
    op.drop_table('unresolved_labels')
    op.drop_table('collection_items')
    op.drop_table('track_artists')
    op.alter_column('artists', 'discogs_artist_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('artists', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('artists', 'source')
    op.drop_column('artists', 'resolved')
    op.alter_column('labels', 'discogs_label_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('labels', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('labels', 'source')
    op.drop_column('labels', 'resolved')
    op.alter_column('releases', 'discogs_release_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('releases', 'discogs_release_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.add_column('labels', sa.Column('resolved', sa.INTEGER(), server_default=sa.text('0'), nullable=False))
    op.add_column('labels', sa.Column('source', sa.TEXT(), server_default=sa.text("'csv_name_only'"), nullable=False))
    op.alter_column('labels', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('labels', 'discogs_label_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.add_column('artists', sa.Column('resolved', sa.INTEGER(), server_default=sa.text('0'), nullable=False))
    op.add_column('artists', sa.Column('source', sa.TEXT(), server_default=sa.text("'csv_name_only'"), nullable=False))
    op.alter_column('artists', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('artists', 'discogs_artist_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.create_table('track_artists',
    sa.Column('discogs_release_id', sa.INTEGER(), nullable=False),
    sa.Column('track_position', sa.TEXT(), nullable=False),
    sa.Column('artist_key', sa.TEXT(), nullable=False),
    sa.Column('role', sa.TEXT(), server_default=sa.text("'track_artist'"), nullable=False),
    sa.Column('source', sa.TEXT(), server_default=sa.text("'discogs_api_pending'"), nullable=False),
    sa.ForeignKeyConstraint(['discogs_release_id', 'track_position'], ['tracks.discogs_release_id', 'tracks.track_position'], ),
    sa.PrimaryKeyConstraint('discogs_release_id', 'track_position', 'artist_key', 'role')
    )
    op.create_table('collection_items',
    sa.Column('discogs_release_id', sa.INTEGER(), nullable=True),
    sa.Column('collection_folder', sa.TEXT(), nullable=True),
    sa.Column('date_added', sa.TEXT(), nullable=True),
    sa.Column('media_condition', sa.TEXT(), nullable=True),
    sa.Column('sleeve_condition', sa.TEXT(), nullable=True),
    sa.Column('collection_notes', sa.TEXT(), nullable=True),
    sa.Column('rating', sa.TEXT(), nullable=True),
    sa.Column('imported_at', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['discogs_release_id'], ['releases.discogs_release_id'], ),
    sa.PrimaryKeyConstraint('discogs_release_id')
    )
    op.create_table('unresolved_labels',
    sa.Column('unresolved_label_key', sa.TEXT(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('normalized_name', sa.TEXT(), nullable=False),
    sa.Column('occurrence_count', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.TEXT(), nullable=False),
    sa.Column('updated_at', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('unresolved_label_key')
    )
    op.create_index(op.f('idx_unresolved_labels_normalized'), 'unresolved_labels', ['normalized_name'], unique=False)
    op.create_table('release_artists',
    sa.Column('discogs_release_id', sa.INTEGER(), nullable=False),
    sa.Column('artist_key', sa.TEXT(), nullable=False),
    sa.Column('role', sa.TEXT(), server_default=sa.text("'primary_release_artist'"), nullable=False),
    sa.Column('position', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('source', sa.TEXT(), server_default=sa.text("'csv_artist_field'"), nullable=False),
    sa.ForeignKeyConstraint(['discogs_release_id'], ['releases.discogs_release_id'], ),
    sa.PrimaryKeyConstraint('discogs_release_id', 'artist_key', 'role', 'position')
    )
    op.create_index(op.f('idx_release_artists_artist_key'), 'release_artists', ['artist_key'], unique=False)
    op.create_table('unresolved_artists',
    sa.Column('unresolved_artist_key', sa.TEXT(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('normalized_name', sa.TEXT(), nullable=False),
    sa.Column('occurrence_count', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.TEXT(), nullable=False),
    sa.Column('updated_at', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('unresolved_artist_key')
    )
    op.create_index(op.f('idx_unresolved_artists_normalized'), 'unresolved_artists', ['normalized_name'], unique=False)
    op.create_table('review_queue',
    sa.Column('review_id', sa.INTEGER(), nullable=True),
    sa.Column('entity_type', sa.TEXT(), nullable=False),
    sa.Column('entity_key', sa.TEXT(), nullable=False),
    sa.Column('service', sa.TEXT(), nullable=False),
    sa.Column('reason', sa.TEXT(), nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'open'"), nullable=False),
    sa.Column('payload_json', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TEXT(), nullable=False),
    sa.Column('updated_at', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_table('release_labels',
    sa.Column('discogs_release_id', sa.INTEGER(), nullable=False),
    sa.Column('label_key', sa.TEXT(), nullable=False),
    sa.Column('position', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('source', sa.TEXT(), server_default=sa.text("'csv_label_field'"), nullable=False),
    sa.ForeignKeyConstraint(['discogs_release_id'], ['releases.discogs_release_id'], ),
    sa.PrimaryKeyConstraint('discogs_release_id', 'label_key', 'position')
    )
    op.create_index(op.f('idx_release_labels_label_key'), 'release_labels', ['label_key'], unique=False)
    op.create_table('external_identities',
    sa.Column('entity_type', sa.TEXT(), nullable=False),
    sa.Column('entity_key', sa.TEXT(), nullable=False),
    sa.Column('service', sa.TEXT(), nullable=False),
    sa.Column('external_id', sa.TEXT(), nullable=True),
    sa.Column('url', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'unverified'"), nullable=False),
    sa.Column('confidence', sa.INTEGER(), nullable=True),
    sa.Column('source', sa.TEXT(), nullable=True),
    sa.Column('last_checked_at', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TEXT(), nullable=False),
    sa.Column('updated_at', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('entity_type', 'entity_key', 'service')
    )
    op.create_table('tracks',
    sa.Column('discogs_release_id', sa.INTEGER(), nullable=False),
    sa.Column('track_position', sa.TEXT(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=True),
    sa.Column('duration', sa.TEXT(), nullable=True),
    sa.Column('source', sa.TEXT(), server_default=sa.text("'discogs_api_pending'"), nullable=False),
    sa.ForeignKeyConstraint(['discogs_release_id'], ['releases.discogs_release_id'], ),
    sa.PrimaryKeyConstraint('discogs_release_id', 'track_position')
    )
    # ### end Alembic commands ###
